Repository BryantDesigns/hackathon, pull requests merged in 2021-12, with the labels that each got.

#7 Landing Page Redesign
  index.html
Labels: Landing Page

#11 About page final
  about.html
  style.css
Labels: enhancement

#17 commit for real this time trust me
  contacts.html
Labels: sus
